### ISSUE TITLE
syntax error when dumping method

### ISSUE THREAD

**Issue by erifan** [josharian/compilecmp#11]
```
$ compilecmp -dumpssa (*scanner).digits:*
-bash: syntax error near unexpected token `('
```

Put the method in single or double quotes:
```
$ compilecmp -dumpssa '(*scanner).digits:*'
...
dumping SSA for (*scanner).digits:*:
exit status 1
panic: exit status 1

goroutine 1 [running]:
log.Panic(0xc000321858, 0x1, 0x1)
        /home/erifan01/go-in-use/src/log/log.go:351 +0xac
main.check(...)
        /home/erifan01/gopath/src/compilecmp/main.go:393
main.dumpSSA(0x0, 0x0, 0x70e8fc, 0x6, 0xc000016180, 0xa, 0xc00001a720, 0x25, 0xc000290000, 0x70e2bf, ...)
        /home/erifan01/gopath/src/compilecmp/dumpssa.go:77 +0x1293
main.comparePlatform(0x0, 0x0, 0x70e8fc, 0x6, 0x70e2bf, 0x4)
        /home/erifan01/gopath/src/compilecmp/main.go:268 +0x92c
main.compare(0x70e8fc, 0x6, 0x70e2bf, 0x4)
        /home/erifan01/gopath/src/compilecmp/main.go:196 +0x112
main.main()
        /home/erifan01/gopath/src/compilecmp/main.go:124 +0x447
```

But we can dump this method with:
`GOSSAFUNC=(*scanner).digits:* go build cmd/compile/internal/syntax`

**Comment by josharian** [comment]
This is a matter of how the shell works; there's nothing we can do about it in compilecmp. As you said, the right fix is to put quotes around the method.

**Comment by erifan** [comment]
Enclosing the method with quotes doesn't fix the issue.

**Comment by josharian** [comment]
Oh, I see. Sorry.

**Comment by josharian** [comment]
abb46a4520ffcaa837e3d6969427d06f4ae5b44d makes it so this now generates a better error message:

```
dumping SSA for (*scanner).digits:*:
cannot find package "." in:
	/Users/josh/.compilecmp/c5d7f2f1cb/src/(*scanner)

exit status 1
```

c3f65a5c47eb21d9c09375a61f48cca700e76bd8 fixes the problem. Those heuristics have been a perennial source of bugs. Shame on me for not having started a regression test before now.
